### ISSUE TITLE
Missing domain conversion factor in "Spectral Bandpass Dependence Correction" notebook.

### ISSUE THREAD

**Issue by henczati** [colour-science/colour-ipython#4]
Hi!

The CIE XYZ domain correction (division by 100) seems to be missing in the [Spectral Bandpass Dependence Correction notebook](../blob/59668afe39e7b5011715917ee0ac057124520fe9/notebooks/colorimetry/correction.ipynb)  in `In [3]:` for the `delta_E_CIE1976` computation before mapping the `XYZ_to_Lab` function to the XYZ values.

You use the domain correction e.g. in the [About Reflectance Recovery - Smits (1999) Method notebook](../../colour-website/blob/8891ece7fd0596b45ab59dd19303e62a9ac293bb/ipython/about_reflectance_recovery.ipynb), and you also indicate in the function docstings ([`colour.spectral_to_XYZ`](../../colour/blob/66d797b16fedfd78fee284fc1bbd974a6e6db70e/colour/colorimetry/tristimulus.py#L58-L64), [`colour.XYZ_to_Lab`](../../colour/blob/66d797b16fedfd78fee284fc1bbd974a6e6db70e/colour/models/cie_lab.py#L68)) that value correction should be applied.

**Comment by KelSolaar** [comment]
Thanks for picking up that one!
